Script started on 2022-01-20 13:08:06-05:00 [TERM="xterm-256color" TTY="/dev/pts/2" COLUMNS="112" LINES="24"]
]0;sth6@gold08: ~/cs/214/labs/02[01;32msth6@gold08[00m:[01;34m~/cs/214/labs/02[00m$ cat s example6.lex example6.y
%{
#include <stdio.h>
#include <stdlib.h>           /* atoi() */
#include <string.h>           /* strcmp() */
#include "example6.tab.h"
%}
%%
[0-9]+                  yylval = atoi(yytext); return NUMBER;
heat                    return TOKHEAT;
on|off                  yylval = !strcmp(yytext,"on"); return STATE;
set                     return TOKSET;
temperature             return TOKTEMPERATURE;
humidity                return TOKHUMIDITY;
\n                      /* ignore end of line */;
[ \t]+                  /* ignore whitespace */;
%%
%{
#include <stdio.h>
#include <string.h>

/* declarations */
int yylex (void);
void yyerror (char const *);
int yyparse(void);

/* definitions */ 
void yyerror(const char *str) {
        fprintf(stderr,"error: %s\n",str);
}
 
int yywrap() {
        return 1;
} 
 
int main() {
        yyparse();
} 

%}

%token NUMBER TOKHEAT STATE TOKSET TOKTEMPERATURE TOKHUMIDITY
%%

commands: /* empty */
        | commands command
        ;

command:
        heat_switch
        | temperature_set
        | humidity_set
        ;

heat_switch:
        TOKHEAT STATE
        {
                if ($2) {  /* if STATE == 1 */
                        printf("\tHeat turned on\n");
                } else {
                        printf("\tHeat turned off\n");
                }
        }
        ;

humidity_set: 
        TOKSET TOKHUMIDITY NUMBER
        {
                printf("\tHumidity set to %d\n",$3);
        }
        ;

temperature_set: 
        TOKSET TOKTEMPERATURE NUMBER
        {
                printf("\tTemperature set to %d\n",$3);
        }
        ;]0;sth6@gold08: ~/cs/214/labs/02[01;32msth6@gold08[00m:[01;34m~/cs/214/labs/02[00m$ flex x example6.lex
]0;sth6@gold08: ~/cs/214/labs/02[01;32msth6@gold08[00m:[01;34m~/cs/214/labs/02[00m$ bison -d example6y .y
]0;sth6@gold08: ~/cs/214/labs/02[01;32msth6@gold08[00m:[01;34m~/cs/214/labs/02[00m$ gcc lex, .yy.c example6.tab.c -o example6
]0;sth6@gold08: ~/cs/214/labs/02[01;32msth6@gold08[00m:[01;34m~/cs/214/labs/02[00m$ ./example6
set temperature to 70
to	Temperature set to 70
set temperature 65
	Temperature set to 65
heat on
	Heat turned on
heat off
	Heat turned off
set humidity 35
	Humidity set to 35
exit
exit]0;sth6@gold08: ~/cs/214/labs/02[01;32msth6@gold08[00m:[01;34m~/cs/214/labs/02[00m$ ext it
exit

Script done on 2022-01-20 13:10:01-05:00 [COMMAND_EXIT_CODE="0"]
