Script started on 2022-02-10 12:25:34-05:00 [TERM="xterm-256color" TTY="/dev/pts/0" COLUMNS="80" LINES="24"]
]0;sth6@gold19: ~/cs/214/labs/05/clojure[01;32msth6@gold19[00m:[01;34m~/cs/214/labs/05/clojure[00m$ clojure
[KClojure 1.10.1
[K(filter (fn [x] (or (neg? x) (odd? x))) [-1 1 -2 2 -3 3 -4 4])[Kuser=> [Kuser=> (filter (fn [x] (or (neg? x) (odd? x))) [-1 1 -2 2 -3 3 -4 4])                                                              (defn negate [sequence[ ][sequence] (map (fn [x][x] (* x -1)(* x -1))(fn [x] (* x -1)) see quence )user=> (defn negate [sequence] (map (fn [x] (* x -1)) sequence ))user=> (defn negate [sequence] (map (fn [x] (* x -1)) sequence ))user=> [K(defn negate [sequence] (map (fn [x] (* x -1)) sequence ))
[K#'user/negate
user=> [Kuser=> [Kuser=> (negate [-1 2 ][-1 2 ]30   -3][-1 2 -3])user=> (negate [-1 2 -3])user=> [K(negate [-1 2 -3])
(1 -2 3)
user=> [Kuser=> [Kuser=> (negate [4 -5 6][4 -5 6])user=> (negate [4 -5 6])user=> [K(negate [4 -5 6])
(-4 5 -6)
user=> [Kuser=> [Kuser=> 
[K]0;sth6@gold19: ~/cs/214/labs/05/clojure[01;32msth6@gold19[00m:[01;34m~/cs/214/labs/05/clojure[00m$ exit

Script done on 2022-02-10 12:26:18-05:00 [COMMAND_EXIT_CODE="0"]
